### ISSUE TITLE
Feature Request: Support for Delta Metrics

### ISSUE THREAD

**Issue by jammiemil** [influxdata/influxdb-observability#6]
I've raised an issue semi related to this against the Opentelemetry-dotnet however it would make sense for this conversion to have support for Delta Type metrics as well as cumulative since Influxdb is happy storing/Querying both.

My specific issue is that the dotnet package for Opentelemetry only seems to send Delta to metrics right now which is making it very hard for me to consume these metrics via Telegraf since Delta metrics are dropped, but i think theres merit to 'fixing' both ends of this use case:

https://github.com/open-telemetry/opentelemetry-dotnet/issues/2290

**Comment by j-kap-t** [comment]
@jacobmarble would you be interested in a PR for this issue in otel2influx?

**Comment by jacobmarble** [comment]
Closed by #245 . Thanks @garry-cairns !
